CREATE DATABASE playlist;
use playlist;

CREATE TABLE IF NOT EXISTS PLAYLIST(ID INTEGER PRIMARY KEY AUTO_INCREMENT, NAME TEXT);
CREATE TABLE IF NOT EXISTS VIDEO(ID INTEGER PRIMARY KEY AUTO_INCREMENT, TITLE TEXT, THUMBNAIL TEXT);
CREATE TABLE IF NOT EXISTS PLAYLIST_VIDEO (ID INTEGER PRIMARY KEY AUTO_INCREMENT, PLAYLIST_ID INTEGER, VIDEO_ID INTEGER);
